Refactor Modal Visible parameter and state management
Megabit/Blazorise pull request #2957
Opened 2021-09-22 10:21 UTC by stsrki

closes #2810 Modal Closing is an Action instead of an EventCallback

I have refactored the `Visible` parameter and `Closing` event. Instead of doing all the logic in the `Visible` setter, I have moved it to the `SetParametersAsync` lifecycle.

- The benefit of this is that the `Closing` event can now be properly awaited.
- The disadvantage is that `Visible` is used only as a hint for us that the parameter was received by the Blazot lifecycle. It should never be used directly as that would leave it in a bad state, eg. `modal.Visible = true`.

2021-09-26 23:37 UTC, David-Moreira requested changes
Tested on bootstrap, looking good.

Update Doc Attributes, `Closing` is now wrong? Also missing alot of attributes.
![image](https://user-images.githubusercontent.com/22283161/134828049-bee06042-ef42-4462-ac79-051a5dbe4706.png)

Two async calls, setup Async?
![image](https://user-images.githubusercontent.com/22283161/134828040-9d3f2444-3817-411b-acf1-ec9e07bb6841.png)

Could `Opening` and `Closing` be EventCallbacks? Or you think it's not worth it?
Also if there's a `Closed` EventCallback, maybe we should introduce an `Opened` EventCallback?
![image](https://user-images.githubusercontent.com/22283161/134828081-bec03adb-178c-4ede-846a-c0135f615819.png)

2021-09-26 23:37 UTC, David-Moreira commented on Source/Blazorise.Bulma/wwwroot/blazorise.bulma.js
> +                const modalBody = element.querySelector('.modal-card-body');
Forgot material.js?

2021-09-26 23:37 UTC, David-Moreira commented on Source/Blazorise/Components/Modal/Modal.razor.cs
> +                }
If these are always done in 'bulk' maybe you can extract these into a method with a bool argument?

2021-09-27 14:33 UTC, stsrki commented on Source/Blazorise.Bulma/wwwroot/blazorise.bulma.js
> +                const modalBody = element.querySelector('.modal-card-body');
Done

2021-09-27 15:11 UTC, njannink commented
Since setting the Visible paramater isn't really a good idea, because it will leave the component in a bad state. Wouldnt it be better to make the setter private or protected?

2021-09-27 19:40 UTC, stsrki commented
> Since setting the Visible parameter isn't really a good idea, because it will leave the component in a bad state. Wouldnt it be better to make the setter private or protected?

Every parameter must be made public and that is Blazor constraint. Otherwise, it will not compile. With the changes in this PR the use of the `Visible` parameter is made in the right way. Meaning it can only be defined declaratively. And if you need to define it imperatively, you still have the option to use `Show()` and `Hide()`.

2021-09-27 20:04 UTC, merged