Docs update for Autocomplete dropdown functionality
Megabit/Blazorise pull request #4672
Opened 2023-03-13 18:44 UTC by coryrwest

In order to make the Autocomplete pop the whole list on click (like a normal select list), you need to set MinLength to 0. It took me a long time to figure that out. A simple docs update will make it more clear for future developers.

I hope my branch name is appropriate.

2023-03-13 18:45 UTC, coryrwest commented
I have read the CLA Document and I hereby sign the CLA

2023-03-13 19:15 UTC, David-Moreira requested changes

2023-03-13 19:15 UTC, David-Moreira commented on Documentation/Blazorise.Docs/Pages/Docs/Extensions/Autocomplete/AutocompletePage.razor
> +        Minimum number of character needed to start search. Set this to 0 make the Autocomplete function like a dropdown.
"to 0 **to** make..."
The documentation should also be reflected on the component itself, if you don't mind making that change also. Thanks!

2023-03-18 09:27 UTC, David-Moreira approved these changes
LGTM. Thanks for the contribution.
@stsrki go ahead and merge this in if you have no complaints.

2023-03-18 15:33 UTC, stsrki approved these changes

2023-03-18 15:34 UTC, stsrki commented
No complaints. Looking good. Thank you @coryrwest

2023-03-18 15:34 UTC, merged